### ISSUE TITLE
Transaction Management

### ISSUE THREAD

**Issue by teneshvignesan** [teneshvignesan/netbalance-app#2]
### Description
 Implement transaction management, allowing users to record income and expenses.

### Acceptance Criteria

- Users can create a new transaction.
- Users can edit wallet transactions.
- Users can delete a transactions.
- User can manage their own transactions.

### Tasks

- [ ]  Create transaction creation interface.
- [ ]  Implement editing functionality.
- [ ]  Develop transaction deletion feature.
- [ ]  Integrate transactions list display.

### Dependencies:

- None

#### Additional Notes: 

- None
