### ISSUE TITLE
Currency Conversion

### ISSUE THREAD

**Issue by teneshvignesan** [teneshvignesan/netbalance-app#3]
### Description
 Enable currency conversion using an external API with hourly updates to maintain the local database

### Acceptance Criteria

- Fetch currency data with a base currency (USD).
- Update the local database every hour.

### Tasks

- [ ]  Integrate the external currency API.
- [ ]  Implement hourly updates to the local database.
- [ ]  Develop logic for currency conversion based on reference with base currency conversion table.

### Dependencies:

- None

#### Additional Notes: 

- None
