### ISSUE TITLE
Account Management

### ISSUE THREAD

**Issue by teneshvignesan** [teneshvignesan/netbalance-app#5]
### Description
Develop a user account table for managing user details.

### Acceptance Criteria

- Users cannot create a new account. Account should be created on new user sign up.
- Users can edit account details.
- Users can delete an account.
- Users can manage their own account.

### Tasks

- [ ]  Create account creation logic with Supabase and  Oauth.
- [ ]  Implement editing functionality.
- [ ]  Develop account deletion feature.
- [ ]  Integrate account display.

### Dependencies:

- None

#### Additional Notes: 

- None
